### ISSUE TITLE
email field  in user profile (HTTP backend)

### ISSUE THREAD

**Issue by diver-ua** [babelouest/glewlwyd#68] opened 2019-11-29 09:43 UTC
Some OpenID-connect clients authenticating by email field in profile - and that field is missing in the HTTP user profile
Is there a chance to get **generated** email field, by providing some template to the HTTP backend?

**Comment by babelouest** [comment] 2019-11-29 12:50
Hello @diver-ua ,

I don't understand what you mean by `Some OpenID-connect clients authenticating by email field in profile`. In Glewlwyd, the users are authenticating with their username field. The username can be filled with the e-mail address but not necessarily.

But I've been thinking about a new easy to make authentication scheme that could help you and others in the future.

Instead of adding more functionalities to the HTTP backend module, I can make a HTTP authentication scheme. This scheme would be used in addition to another user backend like database or LDAP, so you need to add all the users in the backend first, but they could authenticate via a HTTP service and behave like "normal" users, i.e. having different scopes, having any additional properties like e-mail, full name, etc.

What do you think?

**Comment by diver-ua** [comment] 2019-11-29 16:38
Yes. In Glewlwyd they are. But, the 1c accounting software is fetching user email from the auth server,and itt's using email address to link openid client with user in its own database. It not using username field, for some unknown reason...
Yes, I agree - it's stupid and complicated. But that is proprietary software, and it's stupid limitations are so frustrating...

**Comment by babelouest** [comment] 2019-11-29 18:55
I imagine you have to work with closed-source software, but I'd rather not adding this kind of optional functionalities to this backend, which is small and limited by design.
The primary goal of this backend is to provide a connection between a webservice with HTTTP basic authentication and an OAuth2 or OIDC service, without having to store more personal data than needed, because RGPD and stuff.

That's why for your needs, I think a database backend and a soon-to-be released HTTP Basic auth scheme will be better. Also, this new scheme is easy for me to develop, and will most likely avoid having to maintain future bugs on new faetures in the .

**Comment by babelouest** [comment] 2019-11-30 20:47
@diver-ua ,

I added the HTTP Basic authentication scheme to help you with your requirements, you can look at the [documentation](https://github.com/babelouest/glewlwyd/blob/master/docs/GETTING_STARTED.md#http-basic-authentication-scheme) to help you configure it.

**Comment by diver-ua** [comment] 2019-12-02 16:35
I just needed to get it working somehow.
I got it working by dirty-hacking (sorry)


```
diff --git a/src/plugin/protocol_oidc.c b/src/plugin/protocol_oidc.c
index 62da9a7..cf5fd47 100644
--- a/src/plugin/protocol_oidc.c
+++ b/src/plugin/protocol_oidc.c
@@ -3446,6 +3445,8 @@ static int callback_oidc_authorization(const struct _u_request * request, struct
   ret = G_OK;
   if (u_map_has_key(get_map(request), "state")) {
     state = get_state_param(u_map_get(get_map(request), "state"));
+    if(strncmp(state,"&state=",7)==0)
+       strcpy(state,state+(strlen(state)-32));
   }
diff --git a/src/user/http.c b/src/user/http.c
index 48c4925..ec95d0e 100644
--- a/src/user/http.c
+++ b/src/user/http.c
@@ -150,14 +150,14 @@ json_t * user_module_get(struct config_module * config, const char * username, v
   UNUSED(config);
   UNUSED(username);
   UNUSED(cls);
-  return json_pack("{sis{sssOso}}", "result", G_OK, "user", "username", username, "scope", json_object_get((json_t *)cls, "default-scope"), "enabled", json_true());
+  return json_pack("{sis{sssssOso}}", "result", G_OK, "user", "username",username, "email",username, "scope", json_object_get((json_t *)cls, "default-scope"), "enabled", json_true()); 
 }
 
 json_t * user_module_get_profile(struct config_module * config, const char * username, void * cls) {
   UNUSED(config);
   UNUSED(username);
   UNUSED(cls);
-  return json_pack("{sis{sssOso}}", "result", G_OK, "user", "username", username, "scope", json_object_get((json_t *)cls, "default-scope"), "enabled", json_true());
+  return json_pack("{sis{sssssOso}}", "result", G_OK, "user", "username",username, "email",username, "scope", json_object_get((json_t *)cls, "default-scope"), "enabled", json_true());  
 }
 
 json_t * user_module_is_valid(struct config_module * config, const char * username, json_t * j_user, int mode, void * cls) {

```

**Comment by babelouest** [comment] 2019-12-02 18:04
No problem, but as I said, I won't apply your patch to my repository.

I'm closing the issue then

**Closed by babelouest** 2019-12-02 18:04 UTC
Labels: improvement
