### ISSUE TITLE
[Issue] TOTP code not required for login

### ISSUE THREAD

**Issue by yrammos** [babelouest/glewlwyd#120] opened 2020-06-07 14:42 UTC
**Describe the issue**

Although the TOTP scheme is enabled in Glewlwyd, and a shared secret generated for the user, a one-time password is not required to log in.

**To Reproduce**

Install the TOTP authentication scheme; visit the current user's `/profile.html` page; generate a TOTP secret and save the profile; log out; log in.

**Expected behavior**

I would expect a 6-digit code to be requested upon successful entry of username and password.

**System (please complete the following information):**
 - OS/Environment Ubuntu 18.04
 - Safari, Chrome
 - Latest commit on master (`6e200489a31a080591d7df516c0993d9d134867a`)
 - Built from source (using the updated Jansson and latest libmicrohttpd, per the instructions)
 - Built with default options

Thanks!

**Comment by babelouest** [comment] 2020-06-07 14:56
By default, n-factor authentication schemes are not mandatory to login, you must add the required scheme in the scope "Additional authentication schemes" menu for the specified scope:
https://github.com/babelouest/glewlwyd/blob/master/docs/SCOPE.md

**Comment by yrammos** [comment] 2020-06-07 17:17
@babelouest thank you for this clarification. I'm still discovering the glewlwyd's impressive depth and versatility.

The TOTP function still appears fragile on my setup, likely because of clumsy handling on my part. Following your advice, I added TOTP as an "additional authentication scheme," whereby it was working (almost) as expected. I am saying "almost" because the TOTP codes would only work on second attempt, regardless of the "TOTP window" and "start offset" values (I tried several).

Then I decided to start from scratch, so I removed the TOTP authentication scheme altogether with the intention to reinstall it. Alas, no I cannot log on at all! It appears that my admin user's scopes are no longer recognized.

Would be thankful for advice on how to proceed. Of course I could restart with a fresh user database but I'd like to suppose that this was a production scenario with hundreds of users (in which case starting with a fresh database would not be an option).

Thanks once again for this work.

**Comment by babelouest** [comment] 2020-06-07 18:20
I'll give you a SQL query to reset the scope `g_admin` to its original settings and add this script to the documentation for troubleshooting

**Comment by babelouest** [comment] 2020-06-07 20:38
Here's how to reset scope `g_admin` to default settings:

```SQL
-- remove all n-factor authentication
delete from g_scope_group where gs_id in (select gs_id from g_scope where gs_name='g_admin');
-- set scope settings to password required and 10 minutes session
update g_scope set gs_password_required=1, gs_password_max_age=600 where gs_name='gs_admin';
```

Make sure to backup your database before, just in case something goes wrong.

**Comment by babelouest** [comment] 2020-06-07 20:44
@yrammos , after that, you can log in to the admin page with your user admin using its password

**Comment by yrammos** [comment] 2020-06-07 21:30
@babelouest worked as expected, thank you.

**Comment by yrammos** [comment] 2020-06-08 10:26
@babelouest I am still encountering the occasional authorization failure when TOTP codes are involved. I think this happens if I try to log in using consecutive TOTP codes (i.e. codes generated in consecutive time periods).

More likely than not, this is not a bug but my misunderstanding of the "TOTP window" and "start offset" parameters.

Would you mind clarifying what these parameters mean and, especially, why they are not independent? I suppose the "TOTP window" is the period of validity. What is the "offset" though, and why is it always equal to the "window"? Thankful as ever.

**Comment by babelouest** [comment] 2020-06-08 13:48
Hello @yrammos ,

As a security measure, when you enter a valid TOTP code, you can't reuse the same in the time window, to avoid replay attacks. I'm not sure this relates to your issue though, because I don't know what you mean by *consecutively generated TOTP codes*.

Concerning the dependency between *TOTP window* and *start offset* in the UI, it's a good ol' bug that I'll fix soon, among other related small UI bugs.

The meaning of the *TOTP window* is the duration where a TOTP code is valid. By default the TOTP starts a time Unix Epoch 0 (1970/01/01). The start offset allows to start the TOTP window after Unix Epoch 0. This parameter is part of the [RFC 6238](https://tools.ietf.org/html/rfc6238) but IMO it's overkill. All the TOTP usage I've found set offset to 0.

**Comment by yrammos** [comment] 2020-06-08 14:00
Hello @babelouest, By the mouthful "consecutively generated TOTP codes" I mean simply codes that are generated in adjacent time-windows; for example, codes generated less than one minute apart, if the window is 30 sec.

Regarding the "offset," this is what I suspected. The UI bug explains why I always have to skip at least one period ("window") before logging in again. Thanks, Nicolas. You may close this issue, as far as I'm concerned.

**Comment by babelouest** [comment] 2020-06-08 14:23
The adjacent time-window error might be something else than Glewlwyd, I'll try to reproduce the bug but I've never encountered such problems before. The thing is with the TOTP, you enter the code once, then you're logged in, so I don't see how a user might have to enter multiple TOTP codes in adjacent time-windows.

Anyway, the bug will close itself when I'll push the UI fix.

Thanks a lot!

**Closed** 2020-06-08 17:00 UTC
Labels: improvement, question
