### ISSUE TITLE
"Error while updating user" when not all profile fields are filled in

### ISSUE THREAD

**Issue by sth** [babelouest/glewlwyd#100] opened 2020-02-10 01:41 UTC
**Describe the issue**
When I, for example, try to update the password of the predefined admin user, I get a "Error while updating user". The network console shows that the API request returns "400 Bad request"
 with this response: `["email must be a string (maximum 512 characters)"]`

The request contained `"email":null`, probably because the email field contains no text.

**To Reproduce**
Try to change the password of the predefined "admin" account.
 
**Expected behavior**
Update the user.

**System (please complete the following information):**
Debian buster, Firefox and Chrome, Glewlwyd 2.1.1 (Binary .deb packages from Github release)

**Other notes**
I do *not* have this problem when running the `babelouest/glewlwyd` docker image. There the empty field results in an empty string in the API request, not a `null`.

**Comment by sth** [comment] 2020-02-10 02:06
The `email` is already `null` in the data sent by the server for `/api/user?offset=0&limit=20`. In the docker instance the server sends an empty string. So the problem seems to be server side. I use the **Postgresql** database backend, which is not the default, so maybe that is connected?

In the database itself there are empty strings, not `null` vales, in the `g_user` table. I assume that's correct.

**Comment by babelouest** [comment] 2020-02-10 18:08
Hello @sth ,

Thanks for the issue!

In fact, the problem lies in [Hoel](https://github.com/babelouest/hoel/) library, more precisely [here](https://github.com/babelouest/hoel/blob/master/src/hoel-pgsql.c#L317).

The line 317 should simply say:

```C
if (val == NULL) {
```

I'll make the change in Hoel and release a new version, then the next hoel version will be shipped in Glewlwyd 2.1.1 or 2.2.0 when it'll be released (soon but not this week).
If you need the fix soon I suggest you install [Hoel 1.4.14](https://github.com/babelouest/hoel/releases/latest) when it'll be available.

**Comment by babelouest** [comment] 2020-02-10 21:10
Nope, my bad, the fix isn't that simple because it breaks other parts of the application. I'm working on a real fix then.

**Comment by babelouest** [comment] 2020-02-11 05:35
@sth so now I think I have the bug fixed for real in https://github.com/babelouest/hoel/commit/a41ee55b8e5f4c63fb4a1cf4129c8011227376e1

I'll take a couple of more days to add new tests to avoid regression before releasing 1.4.14 though, but you can use this commit if you need the fix right away.

I'll close this issue when the new hoel version will be included in glewlwyd

**Comment by babelouest** [comment] 2020-02-11 05:38
Meanwhile, if you can confirm the bug is fixed, with this patch don't hesitate!

**Comment by sth** [comment] 2020-02-11 23:25
@babelouest With the new library version it works!

**Closed** 2020-02-22 22:58 UTC
Labels: bug
