### ISSUE TITLE
Getting an unauthorized_client error, when setting a client confidential

### ISSUE THREAD

**Issue by wutzebaer** [babelouest/glewlwyd#53] opened 2019-03-06 16:13 UTC
Hi i cannot get an confidential client to work.

If i uncheck the confidential checkbox everything works fine. But when i check it and set the password to testclient (the clientid is testclient, too) i always get an unauthorized_client response:

```
http-bio-8080-exec-3 06/03/2019 17:07:52,902 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 >> "POST /api/token HTTP/1.1[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,903 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 >> "Authorization: Basic dGVzdGNsaWVudDp0ZXN0Y2xpZW50[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,903 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 >> "Content-Length: 171[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,903 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 >> "Content-Type: application/x-www-form-urlencoded[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,903 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 >> "Host: localhost:4593[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,903 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 >> "Connection: Keep-Alive[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,903 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 >> "User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_144)[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,904 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 >> "Accept-Encoding: gzip,deflate[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,904 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 >> "[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,904 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 >> "grant_type=authorization_code&code=75c8d083-37f3-4103-9178-08817ae47090&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2FXXX%2FREST%2FUser%2FXXX&client_id=testclient"
http-bio-8080-exec-3 06/03/2019 17:07:52,906 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 << "HTTP/1.1 403 Forbidden[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,906 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 << "Connection: Keep-Alive[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,906 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 << "Content-Length: 31[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,906 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 << "Content-Type: application/json[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,906 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 << "Pragma: no-cache[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,906 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 << "Cache-Control: no-store[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,907 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 << "Access-Control-Allow-Credentials: true[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,907 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 << "Access-Control-Allow-Origin: *[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,907 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 << "Date: Wed, 06 Mar 2019 16:07:52 GMT[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,907 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 << "[\r][\n]"
http-bio-8080-exec-3 06/03/2019 17:07:52,907 | DEBUG | org.apache.http.wire | wire | http-outgoing-16 << "{"error":"unauthorized_client"}"
```

Any idea whats wrong with my request?

**Comment by wutzebaer** [comment] 2019-03-06 18:04
it seems that i have to set the "Authorization Types" to "client_credentials" whan using a confident client

**Comment by babelouest** [comment] 2019-03-06 18:16
Hello @wutzebaer ,

I can't reproduce your problem with the default or the test configuration.
You get the error message from [this check](https://github.com/babelouest/glewlwyd/blob/master/src/oauth.c#L148), which is precisely the client validation.

Can you make sure nothing else is changed in the client configuration besides its confidential flag and its password? Also, can you make sure the client has all the required authorization types? (In your case at least `authorization_code` and `code`).

I assume you run a single instance of Glewlwyd, i.e. not a kubernetes farm which all have its single SQLite3 database for example.

> it seems that i have to set the "Authorization Types" to "client_credentials" whan using a confident client

You log says you're using `grant_type=authorization_code` so this should not. Although a bug related to the client auth types has been fixed in a previous version. What version of Glewlwyd are you ising?

**Comment by babelouest** [comment] 2019-03-07 01:14
Also, can you send a screenshot of your client configuration in Glewlwyd? (Hide the sensitive data like url callbacks if needed). I'll try to reproduce your issue with your configuration.

**Comment by wutzebaer** [comment] 2019-03-07 08:19
I started a plain docker version:
docker run --rm -it -p 4593:4593 rafaelhdr/glewlwyd-oauth2-server:quickstart

And configured like that:

![grafik](https://user-images.githubusercontent.com/10062396/53941280-fa0f2480-40b7-11e9-9c52-52a91f7bed49.png)

![grafik](https://user-images.githubusercontent.com/10062396/53941418-4d817280-40b8-11e9-8363-677948f24f58.png)

![grafik](https://user-images.githubusercontent.com/10062396/53941749-38f1aa00-40b9-11e9-8074-f4dae608af00.png)

after getting a code for the testuser on testscope i made this call:

```
http-outgoing-1 >> "POST /api/token HTTP/1.1[\r][\n]"
http-outgoing-1 >> "Authorization: Basic dGVzdGNsaWVudDp0ZXN0Y2xpZW50[\r][\n]"
http-outgoing-1 >> "Content-Length: 171[\r][\n]"
http-outgoing-1 >> "Content-Type: application/x-www-form-urlencoded[\r][\n]"
http-outgoing-1 >> "Host: localhost:4593[\r][\n]"
http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
http-outgoing-1 >> "User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_144)[\r][\n]"
http-outgoing-1 >> "Accept-Encoding: gzip,deflate[\r][\n]"
http-outgoing-1 >> "[\r][\n]"
http-outgoing-1 >> "client_id=testclient&redirect_uri=XXX&code=c7ab7e01-bc2c-4264-9a33-2ca0aeaa29ba&grant_type=authorization_code"
http-outgoing-1 << "HTTP/1.1 200 OK[\r][\n]"
http-outgoing-1 << "Connection: Keep-Alive[\r][\n]"
http-outgoing-1 << "Content-Length: 717[\r][\n]"
http-outgoing-1 << "Content-Type: application/json[\r][\n]"
http-outgoing-1 << "Pragma: no-cache[\r][\n]"
http-outgoing-1 << "Cache-Control: no-store[\r][\n]"
http-outgoing-1 << "Access-Control-Allow-Credentials: true[\r][\n]"
http-outgoing-1 << "Access-Control-Allow-Origin: *[\r][\n]"
http-outgoing-1 << "Date: Thu, 07 Mar 2019 08:16:02 GMT[\r][\n]"
http-outgoing-1 << "[\r][\n]"
http-outgoing-1 << "{"token_type":"bearer","access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJleHBpcmVzX2luIjozNjAwLCJpYXQiOjE1NTE5NDY1NjIsInNhbHQiOiJkU0FqUydRczU0ZmFoM3QtIiwic2NvcGUiOiJ0ZXN0c2NvcGUiLCJ0eXBlIjoiYWNjZXNzX3Rva2VuIiwidXNlcm5hbWUiOiJ0ZXN0dXNlciJ9.3wnUMk4YwDRO6xiOUxr7lDw7VoOEDK6y4lLvluABsvAGrMJU7R7I7s-0T2M2oTyGQsshakphkpWF66SOOigp3Q","refresh_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJjbGllbnRfaWQiOiJ0ZXN0Y2xpZW50IiwiZXhwaXJlc19pbiI6MzYwMCwiaWF0IjoxNTUxOTQ2NTYyLCJzYWx0IjoiQkFlX1o1ZDItX1wiSnhjXCJHIiwic2NvcGUiOiJ0ZXN0c2NvcGUiLCJ0eXBlIjoicmVmcmVzaF90b2tlbiIsInVzZXJuYW1lIjoidGVzdHVzZXIifQ.TyIjC0KzupFwFmo3XsnVQPNdbKxDZr9ysdebi3t9X9kX8pC2TOzfASS7BnhZSSQf-6axIX5LXecgKdK4z82Q4A","iat":1551946562,"expires_in":3600}"
```

So it seems "Authorization Types=authorization_code" seems not to be needed

**Comment by babelouest** [comment] 2019-03-07 15:01
Unfortunately, the docker image is not up to date, it's for demonstration only, you should start with building your own.
If I'm correct, you can simply build a new docker image by cloning [Rafael's repository](https://github.com/rafaelhdr/glewlwyd-oauth2-server), then build with the last release. Something like:

```shell
$ git clone https://github.com/rafaelhdr/glewlwyd-oauth2-server.git
$ cd glewlwyd-oauth2-server
$ make build-quickstart VERSION=1.4.9
```

Then, in your client's authorization types, select both `authorization_code` and `code`.
You assumption on the `authorization_code` not needed may be an old bug fixed since.
What's for sure is that `client_credentials` isn't the correct authorization type if you want to use code authentication. Although, you can select multiple authorization types for a client if you need it.

**Comment by babelouest** [comment] 2019-03-07 17:21
Hello again @wutzebaer ,

I've made some changes in the [branch 1.4](https://github.com/babelouest/glewlwyd/tree/1.4) to add debug messages so we can track errors like you have.

Can you checkout this branch and verify if you still have the problem, and if so, check Glewlwyd's logs?

**Comment by babelouest** [comment] 2019-03-11 02:40
@wutzebaer , any update on this issue?

**Comment by wutzebaer** [comment] 2019-03-11 18:47
@babelouest hi no our customer installed the version with additional logs, but didn't get any output when the api returned unauthorized_client. Our customer gave keycloak a try which worked for us. Thank you for your time!

**Closed** 2019-03-11 18:48 UTC
Labels: can't reproduce

**Comment by babelouest** [comment] 2019-03-11 19:44
No problem, thanks!
