### ISSUE TITLE
[Issue] Authentication scheme for scope not saved

### ISSUE THREAD

**Issue by gergof** [babelouest/glewlwyd#175] opened 2021-02-22 10:57 UTC
**Describe the issue**
I'm testing glewlwyd as a light weight alternative for keycloak, but i came across an issue. I use the docker container with the default configuration (`docker run --rm -it -p 4593:4593 babelouest/glewlwyd`). I created a TOTP scheme and a new scope named test. I added the TOTP scheme as required to the scope but it seems like it isn't persisted.

**To Reproduce**
- Create a new scheme
- Create a scope
- Add the scheme to the scope

**Expected behavior**
To save the schemes.

**Screenshots**
![image](https://user-images.githubusercontent.com/10323997/108698724-1d357780-750d-11eb-8f01-c232278eb5c4.png)
![image](https://user-images.githubusercontent.com/10323997/108698792-2e7e8400-750d-11eb-9c97-3ead4394e9cd.png)
![image](https://user-images.githubusercontent.com/10323997/108698831-376f5580-750d-11eb-8616-72233ee5f6f0.png)
![image](https://user-images.githubusercontent.com/10323997/108698853-3f2efa00-750d-11eb-977d-ce3747e305c3.png)

**System (please complete the following information):**
 - OS/Environment: Debian Stretch
 - Browser used: Chromium 88.0.4324.146
 - Glewlwyd Version: 2.5.2
 - Source installation: docker

**Comment by babelouest** [comment] 2021-02-22 12:45
Hello,

I tried your steps but I can't reproduce your problem, my scope test is saved and if I reload the page and reopen the scope, I can see the otp scheme.
Do you see any message in the logs that might be helpful?

**Comment by gergof** [comment] 2021-02-23 08:48
Here is exactly what I made:

I started the container using `docker run --rm -it -p 4593:4593 -e GLWD_LOG_LEVEL=debug babelouest/glewlwyd:2.5.2`.

This is the complete log output: https://cloud.systest.eu/s/ofeHNRK696r22Cs

And this is the recording of what I was exactly doing: https://cloud.systest.eu/s/M3X4GGYzpGAbq83

I think I've found the cause of the bug: it happens when I don't have a display name set for the scheme. I thought it is an optional field. If it is required it shouldn't let the user submit the form without it.

**Comment by babelouest** [comment] 2021-02-23 16:52
OK I see the problem now, indeed it's when the scheme has no display name. The bug has been fixed in this commit: https://github.com/babelouest/glewlwyd/commit/b34690abbf1ce8dd4919db2344d8993fe6b0385c

Thanks for reporting the bug @gergof !

**Closed** 2021-02-23 16:52 UTC
Labels: bug
