### ISSUE TITLE
Some issue with http://localhost:4593/glewlwyd/<end points> especially, client related.

### ISSUE THREAD

**Issue by vidcentum** [babelouest/glewlwyd#14] opened 2017-03-06 10:07 UTC
@babelouest , I am unable to debug what is the source of the following error.

Issue: I tried add a client through GUI app (webapp). I could not add new client app. I tried again and again and succeeded - not sure why it failed before.

An error dialog pops up saying Error adding client...

Issue: I tried to update a client that was added in the step above. I got error all the time. 

The browser log shows: http://localhost:4593/glewlwyd/client/picominer_dashboard 400 Bad request. 
http://localhost:4593/glewlwyd/<end points> such as user/:user etc are also failing with 4XX errors.

Not sure where the issue is. 

Could you please look into it.  

Sorry for troubling you. 

Best Regards
Maruthi

**Comment by babelouest** [comment] 2017-03-06 12:10
Hi Maruthi,

Can you be more specific about the bug? To reproduce it I need the status of the client before the change, and the value of the fields you want to change. 

Thanks in advance

**Comment by vidcentum** [comment] 2017-03-06 12:15
Hi Nicolas Mora, 

Greetings.

I will collect more information and add it to the issue. And steps to reproduce the issue as well. I will do to by to-night or by tomorrow.

Best Regards
Maruthi

**Comment by babelouest** [comment] 2017-03-06 14:35
Thanks Maruthi,

Please also add the content of the response body, there may be an error message that will help me fix this bug.

/Nicolas

**Comment by vidcentum** [comment] 2017-03-08 15:19
Hi Nicolas,

Sorry. I was tied up with some office work and release. I will submit the test report by this weekend.

Best Regards
Maruthi

**Comment by babelouest** [comment] 2017-03-08 15:31
Hello Maruthi,

No problem, before submitting, please pull the last code, some problems were fixed in the last few days, maybe yours was fixed too.

/Nicolas

**Comment by vidcentum** [comment] 2017-03-08 15:35
Sure. I will get new code and test it. 

Best Regards
Maruthi

**Comment by babelouest** [comment] 2017-03-09 00:05
Also, update your `hoel` library, another bug related to glewlyd has been fixed :-)

/Nicolas

**Comment by vidcentum** [comment] 2017-03-09 00:09
Sure. Thanks, Nocolas.

Best Regards
Maruthi

**Comment by vidcentum** [comment] 2017-03-09 00:52
Hi Nicolas,

Following is the pattern to reproduce the issue. Please check.
1. I built the server (new code pulled) + hoel (new code pulled)
2. Ran the server with all default database settings.

3. Login to the Admin App. - OK.
4. Add "first time" client. - OK.
5. Edit the client -  just add authorization types, delete existing etc. Add redirect URI etc. 
   For the first time it all seemed to be working well.
While updating the first client, an Error was thrown - especially when adding code / token as authorization. I did not see any server side logs.   
6. I restarted the App. 
7. Now tried to add a new client (second client, namely p_my_client_app). It expected that adding second client should be OK. 
8. Now it failed.
    Header:
    Request URL:http://localhost:4593/glewlwyd/client/p_my_client_app
    Request Method:GET 
    Status Code:404 Not Found
    Remote Address:127.0.0.1:4593
  
   Request URL:http://localhost:4593/glewlwyd/client/
   Request Method:POST
   Status Code:400 Bad Request
   Remote Address:127.0.0.1:4593

9. I think, the issue may be in the webapp -  in handling the errors as I did not see any server error logs. I am not sure. I have little programming experience in front-end side; all my years of work is in platform, server side.

Best Regards
Maruthi

**Comment by vidcentum** [comment] 2017-03-09 01:05
Hi Nicolas, 
Just wanted to refer Hydra (OAuth Proxy Server) https://github.com/ory/hydra I am sure you might have seen this. May I request you take a look at it if you haven't seen before. 
I see there is some similarity in Hydra and Glewlwyd. Glewlwyd can quickly become light-weight OAuth server with pluggable Auth providers. 
Currently, glewlwyd uses database, ldap source to resource owner authentication. If glewlwyd takes the route of "Consent App", then glewlwyd will be choice for many light weight environments such as IoT gateways, apps. 

It is just a thought. 

Best Regards
Maruthi

**Comment by babelouest** [comment] 2017-03-09 03:23
Hello Maruthi,

Unfortunately I wasn't able to reproduce your bug, I tried with the parameters you gave me but I'm still missing some data to understand.

I created a first client with the name "first time" and client_id "first time", and with a fake redirect_url parameter, it worked, then I added `code` and `token` auth types and saved, it worked too.
Then I added a new client with name `p_my_client_app`, client_id `p_my_client_app` and a fake redirect_uri too, then saved with success, then edited it and added `code` and `token` auth types, with success too then. All of them had `database` backend.

Can you send me all the input parameters you set in each step, and if it results with an error or not.

In case you have the error 400, can you also send the response body, there should be an error message in it. I don't know what is the system and browser you're using, but you might be able to find some documentation online to debug the http request.

Also, thanks for referring Hydra. I didn't know this one, I'm not familiar with all OAuth2 servers and libraries. I made Glewlwyd for my own use and because there was no OAuth2 server or library in C language as far as I could see, but indeed their approach looks interesting. I had a familiar approach on a plugin model with [Angharad](https://github.com/babelouest/angharad), my house automation server.

But even if it's powerful, a modular approach for the backend authentication would be harder to implement, and it's not my goal at that time, but it's probably not impossible.
If you feel like it, you can implement the modification, it should be no more than patching `user.c` and `client.c` for the backend connexion, and `oauth.c` for the authentication API.

**Comment by vidcentum** [comment] 2017-03-09 05:23
Hi Nocolas,,

Thank you very much for a detailed reply. I will test and attach request, response header. Maybe some small step that is causing this issues in my set up. I will include more details soon.

Yes, I will first put forth a document for your review on pluggable auth backend. And, it is my opportunity to contribute to the server as well. 

Servers like glewlwyd help securing IoT applications (at least to some extent) and to provide single sign on features within enterprise systems mostly trusted but still authentication is needed as out-of-box.

Best Regards
Maruthi

**Comment by vidcentum** [comment] 2017-03-16 13:44
Hi Nicolas,

Due to some other workload, I am unable to spend quality time to test. I will plan testing this from 23 March 2017.

Best Regards
Maruthi

**Comment by babelouest** [comment] 2017-03-16 14:21
Hello Maruthi,

No problem, thanks for the heads up.

**Comment by babelouest** [comment] 2017-04-12 19:02
Hello Maruthi,

Any update on this issue?

**Comment by vidcentum** [comment] 2017-04-13 02:10
Hi Nocolas,

My apologies for some delay in verifying the issue due to some other pressing priorities. 
I will retest with latest code base by to-day and tomorrow and update the issue. 

Best Regards
Maruthi

**Comment by vidcentum** [comment] 2017-04-13 07:35
# Glewlwyd Testing
#### 13 April 2017
#### Installation:
> Follow the Glewlwyd installation procedure - https://github.com/babelouest/glewlwyd

#### Initial Data (MySQL):
> MySQL database is used. Populate the database with initial data. Follow the instruction in https://github.com/babelouest/glewlwyd  

#### Configuration (glewlwyd.conf):
> Follow the configuration instructions
Setup MySQL database etc.

#### Run the Glewlwyd OAuth Server.
```
./glewlwyd --config-file=../config/glewlwyd.conf
```
----
```
Access http://localhost:4593/app/  
```
---

##### Test 1 (Login to the Admin App)
```
Access http://localhost:4593/app/   - OK
Login as Admin (default admin:password) - OK  
```
`Glewlwyd OAuth2 Server` screen appears. - OK

##### Test 2 (Add the first client)
Client Id: client-01
Add client. - OK


##### Test 3 (Edit the first client)
Edit the first client. - OK

##### Test 4 (Delete the first client)
Delete the first client. - OK

----
### Test sequence that resulted in error.
##### Test 5 (Add client (client-id is the same as in test 2))
Client Id: client-01
Add client. - OK
Note: Do not add scopes, authorization types. Just leave them default. Do not click on (+) buttom in the scopes, authorization types UI.

##### Test 6 (Edit client added in the Test 5 above)
Edit the clien - Now add scope, authorization type.
This will lead to error message.
Note: After this error, the client is not getting deleted as well.

> Can a client have without a scope? Maybe yes. The error is observed while updating the client without scopes and authorization types to new scope and authorization types.  
```
Is this a correct test sequence?
```

---

**Comment by babelouest** [comment] 2017-04-13 14:55
Hello Mruthi,

I'm sorry but I still can't reproduce your bug with the data you've given me.
When you say you add a client with client_id client-01, there are information missing. To be valid, a client need all the following data:
`name`: string
`client_id`: string
`redirect_uri`: Array of Objects of type `{name: string, url: string starting with "http://" or "https://")}`

Also, when you talk about an error message, I don't know which one.

So can you report all the following data for me to reproduce your bug:
- Before adding a client, open the javascript console (on Firefox and Chrome, press F12) and let it open.
- Add a new client and send me exactly all the fields you are filling with their values
- If this works, go to the `network` tab in the javascript console and check the last API call, you should see a `POST` API call ending with `/client`, check the result code, it should be '200 OK'
- Edit the same client, and again send me exactly all the data that are in the input fields
- If you still have the error message, tell me what error message it is
- Check in the `console` tab in the javascript console, if you see an error message, report it to me too
- And finally, go to the network console and look for a new API call that should be a `PUT` that ends with `/client/client-01`, check the result, and report it to me too

I suggest you send screenshots of your steps, that will be easier.

Thanks in advance

**Comment by vidcentum** [comment] 2017-05-10 03:11
Hi Nocolas,

Greetings.

I will be able to spend some time after 21 May 2017 and retest the problem. I am sorry. I could not test it due to some hard pressing tasks.

Best Regards
Maruthi

**Comment by haroot** [comment] 2017-07-14 18:56
{"error":"resource not found","message":"no resource available at this address"}
after I dumped SQL init.sql Login button gives this message, before it said you are not Authorized

**Comment by haroot** [comment] 2017-07-14 18:58
https://clicktool.com:3002/webapp/login.html?response_type=token&client_id=g_admin&redirect_uri=..%2fapp%2findex.html&scope=g_admin+g_profile => {"error":"resource not found","message":"no resource available at this address"}

but if I edit the URL  webapp => app it works takes me to login prompt..
https://clicktool.com:3002/app/login.html?response_type=token&client_id=g_admin&redirect_uri=..%2fapp%2findex.html&scope=g_admin+g_profile

**Comment by haroot** [comment] 2017-07-14 19:02
is the default login and password the same as SQL doesn't seem to work... is it g_admin something? that doesn't seem to work pls help ty

**Closed** 2018-06-19 12:49 UTC
Labels: bug, can't reproduce

**Comment by LilyLiu0719** [comment] 2022-03-16 08:19
> * POST
